// <auto-generated />
namespace ZaDvermi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class UserColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserColor));
        
        string IMigrationMetadata.Id
        {
            get { return "201402150545594_UserColor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
